image:
  repository: port-agent
  pullPolicy: IfNotPresent
  tag: local

# If you increase this number, you will need to make sure that the kafka topic has enough partitions
replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

controlThePayloadConfig: ""
secret:
  annotations: {}
  name: ""
  useExistingSecret: false

podServiceAccount:
  name: null

env:
  normal:
    GITLAB_URL: "https://gitlab.com/"
    STREAMER_NAME: "POLLING"
    PORT_ORG_ID: "org_cfIyUvRQ1qYx0gb4"
    PORT_API_BASE_URL: 'https://api.getport.io'
    KAFKA_CONSUMER_GROUP_ID: "org_cfIyUvRQ1qYx0gb4"
    KAFKA_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
    KAFKA_CONSUMER_AUTHENTICATION_MECHANISM: "SCRAM-SHA-512"
    KAFKA_CONSUMER_AUTO_OFFSET_RESET: "largest"
    DETAILED_LOGGING: "true"
    WEBHOOK_VERIFY_SSL: "true"
  secret:
    PORT_CLIENT_ID: "s464qygf8C27TtVyuFNWGsUeFsfipmm9"
    PORT_CLIENT_SECRET: "knOjSMFKbpcqysol9KANN5EmxfSo0MnFwW4D10IR0xMm4fhnkAdiT1A0HBEONgAk"

extraLabels: {}

podAnnotations: {}

podSecurityContext: {}
# Example
  # runAsGroup: 1001
  # runAsUser: 1001
  # fsGroup: 1001
  # fsGroupChangePolicy: "OnRootMismatch"
containerSecurityContext: {}
# Example
  # runAsGroup: 1001
  # runAsUser: 1001
  # allowPrivilegeEscalation: false

extraVolumes: []

extraVolumeMounts: []

rolloutStrategy: "Recreate"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

nodeSelector: {}

tolerations: []

affinity: {}

selfSignedCertificate:
  enabled: false
  certificate: ""
  secret:
    name: ""
    key: crt
    useExistingSecret: false
