{{- $resyncOnInstall := ternary .Values.workload.cron.resyncOnInstall true (hasKey .Values.workload.cron "resyncOnInstall") }}
{{- $resyncOnUpgrade := ternary .Values.workload.cron.resyncOnUpgrade true (hasKey .Values.workload.cron "resyncOnUpgrade") }}
{{- if and (eq .Values.workload.kind "CronJob") (or $resyncOnInstall $resyncOnUpgrade) }}
{{- $jobName := (print (randAlphaNum 4) "-" .Release.Revision) | lower }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  name: init-sync-{{ .Release.Name }}-{{ $jobName }}
  labels:
    {{- include "port-ocean.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 180
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "port-ocean.labels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 180
      securityContext:
        {{- if .Values.podSecurityContext }}
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        {{- end }}
      containers:
        - name: kubectl
          image: {{ .Values.workload.cron.kubectlImage }}
          command: [ "sh", "-c" ]
          securityContext:
            {{- if .Values.containerSecurityContext }}
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
            {{- end }}
          resources:
            {{- if .Values.resources }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "port-ocean.cron.job-query-rbac-prefix" . }}-sa-token
                  key: token
          args:
            - kubectl create job --from=cronjob/{{ include "port-ocean.cronJobName" . }} init-sync-{{ $jobName }} --token=$TOKEN
      restartPolicy: Never
{{- end }}
