apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocean-gateway.fullname" . }}-metrics
  labels:
    {{- include "ocean-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ocean-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: metrics
