{{- if eq (include "ocean-gateway.redisSecretCreate" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-gateway.secretName" . }}
  labels:
    {{- include "ocean-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $password := include "ocean-gateway.redisPassword" . }}
  {{- if $password }}
  REDIS_OCEAN_GATEWAY_PASSWORD: {{ $password | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.username }}
  REDIS_OCEAN_GATEWAY_USERNAME: {{ .Values.redis.username | b64enc | quote }}
  {{- end }}
{{- end }}
