apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocean-gateway.fullname" . }}
  labels:
    {{- include "ocean-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "ocean-gateway.selectorLabels" . | nindent 4 }}
