{{- if eq .Values.secret.useExistingSecret false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-k8s-exporter.secretName" . }}
  labels:
    {{- include "port-k8s-exporter.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: opaque
data:
  PORT_CLIENT_ID: {{ required "Port Client ID is required" .Values.secret.secrets.portClientId | b64enc }}
  PORT_CLIENT_SECRET: {{ required "Port Client Secret is required" .Values.secret.secrets.portClientSecret | b64enc }}
{{- end }}