{{- if .Values.podServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "port-ocean.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .Values.podServiceAccount.annotations | toYaml | nindent 4 }}
  labels:
    {{- include "port-ocean.labels" . | nindent 4 }}
{{- end }}