name: Helm Chart Validation

on:
  pull_request:
    paths:
      - charts/port-ocean/**

jobs:
  validate:
    defaults:
      run:
        working-directory: charts/port-ocean/
    runs-on: ubuntu-latest
    name: Validate Helm Chart

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Lint Helm Chart
      run: helm lint .

    - name: Build dependencies of Helm Chart
      run: helm dependency build

    - name: Validate Helm Chart
      run: |
        helm template --set port.clientId=test --set port.clientSecret=test --set configMap.config=test . | kubectl apply --dry-run=client -f -
