name: Helm Chart Validation

on:
  pull_request:
    paths:
      - charts/port-agent/**

jobs:
  validate:
    defaults:
      run:
        working-directory: charts/port-agent/
    runs-on: ubuntu-latest
    name: Validate Helm Chart

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0

    - name: Lint Helm Chart
      run: helm lint .

    - name: Validate Helm Chart
      run: |
        helm template --set env.normal.PORT_ORG_ID=test_org \
        --set env.normal.KAFKA_CONSUMER_GROUP_ID=test_group_id \
        --set env.secret.PORT_CLIENT_ID=test \
        --set env.secret.PORT_CLIENT_SECRET=test . | kubectl apply --dry-run=client -f -
